// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvK4zsqHgim4xSYmUI4-ND-lCercK9OVw',
    appId: '1:452116105865:web:24bc0ff513a882fe6e9458',
    messagingSenderId: '452116105865',
    projectId: 'mindink-379ed',
    authDomain: 'mindink-379ed.firebaseapp.com',
    storageBucket: 'mindink-379ed.firebasestorage.app',
    measurementId: 'G-Z1DF2JC3S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZhZtBKsCNfMH-XcKFOFkZF_sPQaCeXk',
    appId: '1:452116105865:android:d06a8bbb92f243e06e9458',
    messagingSenderId: '452116105865',
    projectId: 'mindink-379ed',
    storageBucket: 'mindink-379ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyagClZkyEAs8NfopURV1In2Hk2FVd3Ww',
    appId: '1:452116105865:ios:4e566a802f61b9c96e9458',
    messagingSenderId: '452116105865',
    projectId: 'mindink-379ed',
    storageBucket: 'mindink-379ed.firebasestorage.app',
    iosBundleId: 'com.example.noteTakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyagClZkyEAs8NfopURV1In2Hk2FVd3Ww',
    appId: '1:452116105865:ios:4e566a802f61b9c96e9458',
    messagingSenderId: '452116105865',
    projectId: 'mindink-379ed',
    storageBucket: 'mindink-379ed.firebasestorage.app',
    iosBundleId: 'com.example.noteTakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvK4zsqHgim4xSYmUI4-ND-lCercK9OVw',
    appId: '1:452116105865:web:b9ccfc674ef00f456e9458',
    messagingSenderId: '452116105865',
    projectId: 'mindink-379ed',
    authDomain: 'mindink-379ed.firebaseapp.com',
    storageBucket: 'mindink-379ed.firebasestorage.app',
    measurementId: 'G-VYHLHHCL7K',
  );
}
